# Derived from 
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
- hosts: localhost
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - npm
          - python3-pip
          - python3-setuptools
          - software-properties-common
          - virtualenv
        state: latest
        update_cache: true
    
    - name: Cleanup existing docker
      apt:
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

- name: MQTT Playbook
  import_playbook: mqtt.yaml

- name: Node Red Playbook
  import_playbook: node_red.yaml

- name: Docker volume setup
  import_playbook: directory_setup.yaml

- name: Docker Compose 
  import_playbook: compose.yaml


